language: generic 
sudo: required
servies:
  - docker

before_install:
  - docker build -t nowertis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nowertis/docker-react npm run test